# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-vm
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: preemptible_and_regular_instance_templates
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-vm
    sourceType: git
  version: 7.9.0
  actuationTool:
    type: Terraform
    version: '>=0.13.0'
  examples:
  - name: additional_disks
    location: examples/instance_template/additional_disks
  - name: alias_ip_range
    location: examples/instance_template/alias_ip_range
  - name: autoscaler
    location: examples/mig/autoscaler
  - name: disk_snapshot
    location: examples/compute_instance/disk_snapshot
  - name: encrypted_disks
    location: examples/instance_template/encrypted_disks
  - name: full
    location: examples/mig/full
  - name: full
    location: examples/umig/full
  - name: healthcheck
    location: examples/mig/healthcheck
  - name: multiple_interfaces
    location: examples/compute_instance/multiple_interfaces
  - name: named_ports
    location: examples/umig/named_ports
  - name: next_hop
    location: examples/compute_instance/next_hop
  - name: simple
    location: examples/compute_instance/simple
  - name: simple
    location: examples/instance_template/simple
  - name: simple
    location: examples/mig/simple
  - name: simple
    location: examples/mig_with_percent/simple
  - name: simple
    location: examples/preemptible_and_regular_instance_templates/simple
  - name: simple
    location: examples/umig/simple
  - name: static_ips
    location: examples/umig/static_ips
  - name: tags
    location: examples/compute_instance/tags
  variables:
  - name: access_config
    description: Access configurations, i.e. IPs via which the VM instance can be accessed via the Internet.
    type: |-
      list(object({
          nat_ip       = string
          network_tier = string
        }))
    default: []
    required: false
  - name: additional_disks
    description: List of maps of additional disks. See https://www.terraform.io/docs/providers/google/r/compute_instance_template#disk_name
    type: |-
      list(object({
          disk_name    = string
          device_name  = string
          auto_delete  = bool
          boot         = bool
          disk_size_gb = number
          disk_type    = string
          disk_labels  = map(string)
        }))
    default: []
    required: false
  - name: auto_delete
    description: Whether or not the boot disk should be auto-deleted
    type: bool
    default: true
    required: false
  - name: can_ip_forward
    description: Enable IP forwarding, for NAT instances for example
    type: string
    default: "false"
    required: false
  - name: disk_size_gb
    description: Boot disk size in GB
    type: string
    default: "100"
    required: false
  - name: disk_type
    description: Boot disk type, can be either pd-ssd, local-ssd, or pd-standard
    type: string
    default: pd-standard
    required: false
  - name: ipv6_access_config
    description: IPv6 access configurations. Currently a max of 1 IPv6 access configuration is supported. If not specified, the instance will have no external IPv6 Internet access.
    type: |-
      list(object({
          network_tier = string
        }))
    default: []
    required: false
  - name: labels
    description: Labels, provided as a map
    type: map(string)
    default: {}
    required: false
  - name: machine_type
    description: Machine type to create, e.g. n1-standard-1
    type: string
    default: n1-standard-1
    required: false
  - name: metadata
    description: Metadata, provided as a map
    type: map(string)
    default: {}
    required: false
  - name: name_prefix
    description: Name prefix for the instance template
    type: string
    default: default-it
    required: false
  - name: network
    description: The name or self_link of the network to attach this interface to. Use network attribute for Legacy or Auto subnetted networks and subnetwork for custom subnetted networks.
    type: string
    default: ""
    required: false
  - name: project_id
    description: The GCP project ID
    type: string
    required: false
  - name: service_account
    description: Service account to attach to the instance. See https://www.terraform.io/docs/providers/google/r/compute_instance_template#service_account.
    type: |-
      object({
          email  = string
          scopes = set(string)
        })
    required: true
  - name: source_image
    description: Source disk image. If neither source_image nor source_image_family is specified, defaults to the latest public CentOS image.
    type: string
    default: ""
    required: false
  - name: source_image_family
    description: Source image family. If neither source_image nor source_image_family is specified, defaults to the latest public CentOS image.
    type: string
    default: ""
    required: false
  - name: source_image_project
    description: Project where the source image comes from
    type: string
    default: ""
    required: false
  - name: startup_script
    description: User startup script to run when instances spin up
    type: string
    default: ""
    required: false
  - name: subnetwork
    description: The name of the subnetwork to attach this interface to. The subnetwork must exist in the same region this instance will be created in. Either network or subnetwork must be provided.
    type: string
    default: ""
    required: false
  - name: subnetwork_project
    description: The ID of the project in which the subnetwork belongs. If it is not provided, the provider project is used.
    type: string
    default: ""
    required: false
  - name: tags
    description: Network tags, provided as a list
    type: list(string)
    default: []
    required: false
  outputs:
  - name: preemptible_name
    description: Name of preemptible instance template
  - name: preemptible_self_link
    description: Self-link of preemptible instance template
  - name: regular_name
    description: Name of regular instance template
  - name: regular_self_link
    description: Self-link of regular instance template
  roles:
  - level: Project
    roles:
    - roles/owner
    - roles/compute.admin
    - roles/compute.networkAdmin
    - roles/iam.serviceAccountUser
    - roles/compute.instanceAdmin
  services:
  - cloudresourcemanager.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - compute.googleapis.com
  - iam.googleapis.com
