# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-vm-mig
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Managed Instance Group (MIG)
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-vm
      sourceType: git
      dir: /modules/mig
    version: 13.2.2
    actuationTool:
      flavor: Terraform
      version: ">=1.3.0"
    description: {}
  content:
    examples:
      - name: additional_disks
        location: examples/instance_template/additional_disks
      - name: alias_ip_range
        location: examples/instance_template/alias_ip_range
      - name: autoscaler
        location: examples/mig/autoscaler
      - name: confidential_computing
        location: examples/confidential_computing
      - name: confidential_computing
        location: examples/instance_template/confidential_computing
      - name: confidential_computing_intel
        location: examples/confidential_computing_intel
      - name: disk_snapshot
        location: examples/compute_instance/disk_snapshot
      - name: encrypted_disks
        location: examples/instance_template/encrypted_disks
      - name: full
        location: examples/mig/full
      - name: full
        location: examples/umig/full
      - name: healthcheck
        location: examples/mig/healthcheck
      - name: it_simple_with_sa_creation
        location: examples/it_simple_with_sa_creation
      - name: mig_stateful
        location: examples/mig_stateful
      - name: multiple_interfaces
        location: examples/compute_instance/multiple_interfaces
      - name: named_ports
        location: examples/umig/named_ports
      - name: next_hop
        location: examples/compute_instance/next_hop
      - name: simple
        location: examples/compute_instance/simple
      - name: simple
        location: examples/instance_template/simple
      - name: simple
        location: examples/mig/simple
      - name: simple
        location: examples/mig_with_percent/simple
      - name: simple
        location: examples/preemptible_and_regular_instance_templates/simple
      - name: simple
        location: examples/umig/simple
      - name: static_ips
        location: examples/umig/static_ips
      - name: tags
        location: examples/compute_instance/tags
  interfaces:
    variables:
      - name: project_id
        description: The Google Cloud project ID
        varType: string
        required: true
      - name: region
        description: The Google Cloud region where the managed instance group resides.
        varType: string
        required: true
      - name: mig_name
        description: Managed instance group name. When variable is empty, name will be derived from var.hostname.
        varType: string
        defaultValue: ""
      - name: hostname
        description: Hostname prefix for instances
        varType: string
        defaultValue: default
      - name: target_size
        description: The target number of running instances for this managed instance group. This value should always be explicitly set unless this resource is attached to an autoscaler, in which case it should never be set.
        varType: number
        defaultValue: 1
      - name: instance_template
        description: Instance template self_link used to create compute instances
        varType: string
        required: true
        connections:
          - source:
              source: github.com/terraform-google-modules/terraform-google-vm//modules/instance_template
              version: ">= 12.0"
            spec:
              outputExpr: self_link
      - name: target_pools
        description: The target load balancing pools to assign this group to.
        varType: list(string)
        defaultValue: []
      - name: distribution_policy_target_shape
        description: MIG target distribution shape (EVEN, BALANCED, ANY, ANY_SINGLE_ZONE)
        varType: string
      - name: distribution_policy_zones
        description: The distribution policy, i.e. which zone(s) should instances be create in. Default is all zones in given region.
        varType: list(string)
        defaultValue: []
      - name: stateful_disks
        description: Disks created on the instances that will be preserved on instance delete. https://cloud.google.com/compute/docs/instance-groups/configuring-stateful-disks-in-migs
        varType: |-
          list(object({
              device_name = string
              delete_rule = string
            }))
        defaultValue: []
      - name: stateful_ips
        description: Statful IPs created on the instances that will be preserved on instance delete. https://cloud.google.com/compute/docs/instance-groups/configuring-stateful-ip-addresses-in-migs
        varType: |-
          list(object({
              interface_name = string
              delete_rule    = string
              is_external    = bool
            }))
        defaultValue: []
      - name: update_policy
        description: The rolling update policy. https://www.terraform.io/docs/providers/google/r/compute_region_instance_group_manager#rolling_update_policy
        varType: |-
          list(object({
              max_surge_fixed                = optional(number)
              instance_redistribution_type   = optional(string)
              max_surge_percent              = optional(number)
              max_unavailable_fixed          = optional(number)
              max_unavailable_percent        = optional(number)
              min_ready_sec                  = optional(number)
              replacement_method             = optional(string)
              minimal_action                 = string
              type                           = string
              most_disruptive_allowed_action = optional(string)
            }))
        defaultValue: []
      - name: health_check_name
        description: Health check name. When variable is empty, name will be derived from var.hostname.
        varType: string
        defaultValue: ""
      - name: health_check
        description: Health check to determine whether instances are responsive and able to do work
        varType: |-
          object({
              type                = string
              initial_delay_sec   = number
              check_interval_sec  = number
              healthy_threshold   = number
              timeout_sec         = number
              unhealthy_threshold = number
              response            = string
              proxy_header        = string
              port                = number
              request             = string
              request_path        = string
              host                = string
              enable_logging      = bool
            })
        defaultValue:
          check_interval_sec: 30
          enable_logging: false
          healthy_threshold: 1
          host: ""
          initial_delay_sec: 30
          port: 80
          proxy_header: NONE
          request: ""
          request_path: /
          response: ""
          timeout_sec: 10
          type: ""
          unhealthy_threshold: 5
      - name: autoscaler_name
        description: Autoscaler name. When variable is empty, name will be derived from var.hostname.
        varType: string
        defaultValue: ""
      - name: autoscaling_enabled
        description: Creates an autoscaler for the managed instance group
        varType: string
        defaultValue: "false"
      - name: max_replicas
        description: The maximum number of instances that the autoscaler can scale up to. This is required when creating or updating an autoscaler. The maximum number of replicas should not be lower than minimal number of replicas.
        varType: number
        defaultValue: 10
      - name: min_replicas
        description: The minimum number of replicas that the autoscaler can scale down to. This cannot be less than 0.
        varType: number
        defaultValue: 2
      - name: cooldown_period
        description: The number of seconds that the autoscaler should wait before it starts collecting information from a new instance.
        varType: number
        defaultValue: 60
      - name: autoscaling_mode
        description: Operating mode of the autoscaling policy. If omitted, the default value is ON. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_autoscaler#mode
        varType: string
      - name: autoscaling_cpu
        description: Autoscaling, cpu utilization policy block as single element array. https://www.terraform.io/docs/providers/google/r/compute_autoscaler#cpu_utilization
        varType: |-
          list(object({
              target            = number
              predictive_method = string
            }))
        defaultValue: []
      - name: autoscaling_metric
        description: Autoscaling, metric policy block as single element array. https://www.terraform.io/docs/providers/google/r/compute_autoscaler#metric
        varType: |-
          list(object({
              name   = string
              target = number
              type   = string
            }))
        defaultValue: []
      - name: autoscaling_lb
        description: Autoscaling, load balancing utilization policy block as single element array. https://www.terraform.io/docs/providers/google/r/compute_autoscaler#load_balancing_utilization
        varType: list(map(number))
        defaultValue: []
      - name: scaling_schedules
        description: Autoscaling, scaling schedule block. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_autoscaler#scaling_schedules
        varType: |-
          list(object({
              disabled              = bool
              duration_sec          = number
              min_required_replicas = number
              name                  = string
              schedule              = string
              time_zone             = string
            }))
        defaultValue: []
      - name: autoscaling_scale_in_control
        description: Autoscaling, scale-in control block. https://www.terraform.io/docs/providers/google/r/compute_autoscaler#scale_in_control
        varType: |-
          object({
              fixed_replicas   = number
              percent_replicas = number
              time_window_sec  = number
            })
        defaultValue:
          fixed_replicas: null
          percent_replicas: null
          time_window_sec: null
      - name: named_ports
        description: Named name and named port. https://cloud.google.com/load-balancing/docs/backend-service#named_ports
        varType: |-
          list(object({
              name = string
              port = number
            }))
        defaultValue: []
      - name: wait_for_instances
        description: Whether to wait for all instances to be created/updated before returning. Note that if this is set to true and the operation does not succeed, Terraform will continue trying until it times out.
        varType: string
        defaultValue: "false"
      - name: mig_timeouts
        description: "Times for creation, deleting and updating the MIG resources. Can be helpful when using wait_for_instances to allow a longer VM startup time. "
        varType: |-
          object({
              create = string
              update = string
              delete = string
            })
        defaultValue:
          create: 5m
          delete: 15m
          update: 5m
      - name: labels
        description: Labels, provided as a map
        varType: map(string)
        defaultValue: {}
    outputs:
      - name: apphub_workload_uri
        description: Workload URI in CAIS style to be used by Apphub.
        type:
          - object
          - location: string
            workload_id: string
            workload_uri: string
      - name: health_check_self_links
        description: All self_links of healthchecks created for the instance group.
        type:
          - list
          - string
      - name: instance_group
        description: Instance-group url of managed instance group
        type: string
      - name: instance_group_manager
        description: An instance of google_compute_region_instance_group_manager of the instance group.
        type:
          - object
          - base_instance_name: string
      - name: self_link
        description: Self-link of managed instance group
        type: string
  requirements:
    roles:
      - level: Project
        roles:
          - roles/compute.admin
          - roles/compute.networkAdmin
          - roles/iam.serviceAccountUser
          - roles/iam.serviceAccountAdmin
          - roles/compute.instanceAdmin
          - roles/resourcemanager.projectIamAdmin
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
      - compute.googleapis.com
      - iam.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 4.48, < 7"
      - source: hashicorp/google-beta
        version: ">= 4.48, < 7"
