# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-vm
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: Managed Instance Group (MIG)
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-vm
    sourceType: git
  version: 7.9.0
  actuationTool:
    type: Terraform
    version: '>=0.13.0'
  examples:
  - name: additional_disks
    location: examples/instance_template/additional_disks
  - name: alias_ip_range
    location: examples/instance_template/alias_ip_range
  - name: autoscaler
    location: examples/mig/autoscaler
  - name: disk_snapshot
    location: examples/compute_instance/disk_snapshot
  - name: encrypted_disks
    location: examples/instance_template/encrypted_disks
  - name: full
    location: examples/mig/full
  - name: full
    location: examples/umig/full
  - name: healthcheck
    location: examples/mig/healthcheck
  - name: multiple_interfaces
    location: examples/compute_instance/multiple_interfaces
  - name: named_ports
    location: examples/umig/named_ports
  - name: next_hop
    location: examples/compute_instance/next_hop
  - name: simple
    location: examples/compute_instance/simple
  - name: simple
    location: examples/instance_template/simple
  - name: simple
    location: examples/mig/simple
  - name: simple
    location: examples/mig_with_percent/simple
  - name: simple
    location: examples/preemptible_and_regular_instance_templates/simple
  - name: simple
    location: examples/umig/simple
  - name: static_ips
    location: examples/umig/static_ips
  - name: tags
    location: examples/compute_instance/tags
  variables:
  - name: autoscaler_name
    description: Autoscaler name. When variable is empty, name will be derived from var.hostname.
    type: string
    default: ""
    required: false
  - name: autoscaling_cpu
    description: Autoscaling, cpu utilization policy block as single element array. https://www.terraform.io/docs/providers/google/r/compute_autoscaler#cpu_utilization
    type: |-
      list(object({
          target            = number
          predictive_method = string
        }))
    default: []
    required: false
  - name: autoscaling_enabled
    description: Creates an autoscaler for the managed instance group
    type: string
    default: "false"
    required: false
  - name: autoscaling_lb
    description: Autoscaling, load balancing utilization policy block as single element array. https://www.terraform.io/docs/providers/google/r/compute_autoscaler#load_balancing_utilization
    type: list(map(number))
    default: []
    required: false
  - name: autoscaling_metric
    description: Autoscaling, metric policy block as single element array. https://www.terraform.io/docs/providers/google/r/compute_autoscaler#metric
    type: |-
      list(object({
          name   = string
          target = number
          type   = string
        }))
    default: []
    required: false
  - name: autoscaling_mode
    description: Operating mode of the autoscaling policy. If omitted, the default value is ON. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_autoscaler#mode
    type: string
    required: false
  - name: autoscaling_scale_in_control
    description: Autoscaling, scale-in control block. https://www.terraform.io/docs/providers/google/r/compute_autoscaler#scale_in_control
    type: |-
      object({
          fixed_replicas   = number
          percent_replicas = number
          time_window_sec  = number
        })
    default:
      fixed_replicas: null
      percent_replicas: null
      time_window_sec: null
    required: false
  - name: cooldown_period
    description: The number of seconds that the autoscaler should wait before it starts collecting information from a new instance.
    type: number
    default: 60
    required: false
  - name: distribution_policy_zones
    description: The distribution policy, i.e. which zone(s) should instances be create in. Default is all zones in given region.
    type: list(string)
    default: []
    required: false
  - name: health_check
    description: Health check to determine whether instances are responsive and able to do work
    type: |-
      object({
          type                = string
          initial_delay_sec   = number
          check_interval_sec  = number
          healthy_threshold   = number
          timeout_sec         = number
          unhealthy_threshold = number
          response            = string
          proxy_header        = string
          port                = number
          request             = string
          request_path        = string
          host                = string
          enable_logging      = bool
        })
    default:
      check_interval_sec: 30
      enable_logging: false
      healthy_threshold: 1
      host: ""
      initial_delay_sec: 30
      port: 80
      proxy_header: NONE
      request: ""
      request_path: /
      response: ""
      timeout_sec: 10
      type: ""
      unhealthy_threshold: 5
    required: false
  - name: health_check_name
    description: Health check name. When variable is empty, name will be derived from var.hostname.
    type: string
    default: ""
    required: false
  - name: hostname
    description: Hostname prefix for instances
    type: string
    default: default
    required: false
  - name: instance_template
    description: Instance template self_link used to create compute instances
    type: string
    required: true
  - name: max_replicas
    description: The maximum number of instances that the autoscaler can scale up to. This is required when creating or updating an autoscaler. The maximum number of replicas should not be lower than minimal number of replicas.
    type: number
    default: 10
    required: false
  - name: mig_name
    description: Managed instance group name. When variable is empty, name will be derived from var.hostname.
    type: string
    default: ""
    required: false
  - name: mig_timeouts
    description: 'Times for creation, deleting and updating the MIG resources. Can be helpful when using wait_for_instances to allow a longer VM startup time. '
    type: |-
      object({
          create = string
          update = string
          delete = string
        })
    default:
      create: 5m
      delete: 15m
      update: 5m
    required: false
  - name: min_replicas
    description: The minimum number of replicas that the autoscaler can scale down to. This cannot be less than 0.
    type: number
    default: 2
    required: false
  - name: named_ports
    description: Named name and named port. https://cloud.google.com/load-balancing/docs/backend-service#named_ports
    type: |-
      list(object({
          name = string
          port = number
        }))
    default: []
    required: false
  - name: project_id
    description: The GCP project ID
    type: string
    required: false
  - name: region
    description: The GCP region where the managed instance group resides.
    type: string
    required: true
  - name: scaling_schedules
    description: Autoscaling, scaling schedule block. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_autoscaler#scaling_schedules
    type: |-
      list(object({
          disabled              = bool
          duration_sec          = number
          min_required_replicas = number
          name                  = string
          schedule              = string
          time_zone             = string
        }))
    default: []
    required: false
  - name: stateful_disks
    description: Disks created on the instances that will be preserved on instance delete. https://cloud.google.com/compute/docs/instance-groups/configuring-stateful-disks-in-migs
    type: |-
      list(object({
          device_name = string
          delete_rule = string
        }))
    default: []
    required: false
  - name: target_pools
    description: The target load balancing pools to assign this group to.
    type: list(string)
    default: []
    required: false
  - name: target_size
    description: The target number of running instances for this managed instance group. This value should always be explicitly set unless this resource is attached to an autoscaler, in which case it should never be set.
    type: number
    default: 1
    required: false
  - name: update_policy
    description: The rolling update policy. https://www.terraform.io/docs/providers/google/r/compute_region_instance_group_manager#rolling_update_policy
    type: |-
      list(object({
          max_surge_fixed              = number
          instance_redistribution_type = string
          max_surge_percent            = number
          max_unavailable_fixed        = number
          max_unavailable_percent      = number
          min_ready_sec                = number
          replacement_method           = string
          minimal_action               = string
          type                         = string
        }))
    default: []
    required: false
  - name: wait_for_instances
    description: Whether to wait for all instances to be created/updated before returning. Note that if this is set to true and the operation does not succeed, Terraform will continue trying until it times out.
    type: string
    default: "false"
    required: false
  outputs:
  - name: health_check_self_links
    description: All self_links of healthchecks created for the instance group.
  - name: instance_group
    description: Instance-group url of managed instance group
  - name: instance_group_manager
    description: An instance of google_compute_region_instance_group_manager of the instance group.
  - name: self_link
    description: Self-link of managed instance group
  roles:
  - level: Project
    roles:
    - roles/owner
    - roles/compute.admin
    - roles/compute.networkAdmin
    - roles/iam.serviceAccountUser
    - roles/compute.instanceAdmin
  services:
  - cloudresourcemanager.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - compute.googleapis.com
  - iam.googleapis.com
