# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-vm-mig-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Managed Instance Group (MIG)
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-vm
      sourceType: git
      dir: /modules/mig
  ui:
    input:
      variables:
        autoscaler_name:
          name: autoscaler_name
          title: Autoscaler Name
          regexValidation: ^[a-z][a-z0-9-]{0,61}[a-z0-9]$
          validation: Autoscaler name must be between 1 and 63 characters long, start with a lowercase letter, and can contain lowercase letters, numbers, and hyphens.
        autoscaling_cpu:
          name: autoscaling_cpu
          title: Autoscaling Cpu
          properties:
            predictive_method:
              name: predictive_method
              title: Predictive Method
              enumValueLabels:
                - label: NONE
                  value: NONE
                - label: OPTIMIZE_AVAILABILITY
                  value: OPTIMIZE_AVAILABILITY
            target:
              name: target
              title: Target
              max: 1
        autoscaling_enabled:
          name: autoscaling_enabled
          title: Autoscaling Enabled
        autoscaling_lb:
          name: autoscaling_lb
          title: Autoscaling Lb
          properties:
            target:
              name: target
              title: Target
              max: 1
        autoscaling_metric:
          name: autoscaling_metric
          title: Autoscaling Metric
          properties:
            target:
              name: target
              title: Target
              max: 1
            type:
              name: type
              title: Type
              enumValueLabels:
                - label: GAUGE
                  value: GAUGE
                - label: DELTA_PER_SECOND
                  value: DELTA_PER_SECOND
                - label: DELTA_PER_MINUTE
                  value: DELTA_PER_MINUTE
        autoscaling_mode:
          name: autoscaling_mode
          title: Autoscaling Mode
          enumValueLabels:
            - label: "ON"
              value: "ON"
            - label: ONLY_SCALE_OUT
              value: ONLY_SCALE_OUT
            - label: "OFF"
              value: "OFF"
          level: 1
        autoscaling_scale_in_control:
          name: autoscaling_scale_in_control
          title: Autoscaling Scale In Control
          properties:
            fixed_replicas:
              name: fixed_replicas
              title: Fixed Replicas
            percent_replicas:
              name: percent_replicas
              title: Percent Replicas
              max: 100
        cooldown_period:
          name: cooldown_period
          title: Cooldown Period
        distribution_policy_target_shape:
          name: distribution_policy_target_shape
          title: Distribution Policy Target Shape
          enumValueLabels:
            - label: EVEN
              value: EVEN
            - label: BALANCED
              value: BALANCED
            - label: ANY
              value: ANY
            - label: ANY_SINGLE_ZONE
              value: ANY_SINGLE_ZONE
        distribution_policy_zones:
          name: distribution_policy_zones
          title: Distribution Policy Zones
        health_check:
          name: health_check
          title: Health Check
          properties:
            initial_delay_sec:
              name: initial_delay_sec
              title: Initial Delay Sec
              max: 3600
            port:
              name: port
              title: Port
              min: 1
              max: 65535
            proxy_header:
              name: proxy_header
              title: Proxy Header
              enumValueLabels:
                - label: NONE
                  value: NONE
                - label: PROXY_V1
                  value: PROXY_V1
            type:
              name: type
              title: Type
              enumValueLabels:
                - label: HTTPS
                  value: HTTPS
                - label: HTTP
                  value: HTTP
                - label: TCP
                  value: TCP
                - label: SSL
                  value: SSL
        health_check_name:
          name: health_check_name
          title: Health Check Name
          regexValidation: ^[a-z][a-z0-9-]{0,61}[a-z0-9]$
          validation: Health check name must be between 1 and 63 characters long, start with a lowercase letter, and can contain lowercase letters, numbers, and hyphens.
        hostname:
          name: hostname
          title: Hostname
          regexValidation: ^[a-z][a-z0-9-]{0,61}[a-z0-9]$
          validation: Hostname must be between 1 and 63 characters long, start with a lowercase letter, and can contain lowercase letters, numbers, and hyphens.
          level: 1
        instance_template:
          name: instance_template
          title: Instance Template
          regexValidation: ^https://www.googleapis.com/compute/v1/projects/[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?/(?:global|regions/[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)/instanceTemplates/[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?$
          validation: Invalid template url format, valid format is either https://www.googleapis.com/compute/v1/projects/{project}/regions/{region}/instanceTemplates/{template_name} (regional) or https://www.googleapis.com/compute/v1/projects/{project}/global/instanceTemplates/{template_name} (global).
        labels:
          name: labels
          title: Labels
        max_replicas:
          name: max_replicas
          title: Max Replicas
          level: 1
        mig_name:
          name: mig_name
          title: Mig Name
          regexValidation: ^[a-z][a-z0-9-]{0,61}[a-z0-9]$
          validation: Use lowercase letters, numbers, and hyphens. Start with a letter and end with letter/number. Must be 63 characters or fewer.
          level: 1
        mig_timeouts:
          name: mig_timeouts
          title: Mig Timeouts
        min_replicas:
          name: min_replicas
          title: Min Replicas
          level: 1
        named_ports:
          name: named_ports
          title: Named Ports
          properties:
            name:
              name: name
              title: Port Name
              regexValidation: ^[a-z]([-a-z0-9]{0,61}[a-z0-9])?$
              validation: Port name must be between 1 and 63 characters long, start with a lowercase letter, and can contain lowercase letters, numbers, and hyphens.
            port:
              name: port
              title: Port
              min: 1
              max: 65535
        project_id:
          name: project_id
          title: Project Id
          level: 1
        region:
          name: region
          title: Region
        scaling_schedules:
          name: scaling_schedules
          title: Scaling Schedules
          properties:
            duration_sec:
              name: duration_sec
              title: Duration Sec
              min: 300
            schedule:
              name: schedule
              title: Schedule
              regexValidation: ^([*]|([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])(-([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9]))?)(,([*]|([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])(-([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9]))?))* ([*]|([0-9]|1[0-9]|2[0-3])(-([0-9]|1[0-9]|2[0-3]))?)(,([*]|([0-9]|1[0-9]|2[0-3])(-([0-9]|1[0-9]|2[0-3]))?))* ([*]|([1-9]|1[0-9]|2[0-9]|3[0-1])(-([1-9]|1[0-9]|2[0-9]|3[0-1]))?)(,([*]|([1-9]|1[0-9]|2[0-9]|3[0-1])(-([1-9]|1[0-9]|2[0-9]|3[0-1]))?))* ([*]|([1-9]|1[0-2])(-([1-9]|1[0-2]))?)(,([*]|([1-9]|1[0-2])(-([1-9]|1[0-2]))?))* ([*]|([0-6])(-([0-6]))?)(,([*]|([0-6])(-([0-6]))?))*$
              validation: Schedule must be in cron format.
        stateful_disks:
          name: stateful_disks
          title: Stateful Disks
          properties:
            delete_rule:
              name: delete_rule
              title: Delete Rule
              enumValueLabels:
                - label: NEVER
                  value: NEVER
                - label: ON_PERMANENT_INSTANCE_DELETION
                  value: ON_PERMANENT_INSTANCE_DELETION
        stateful_ips:
          name: stateful_ips
          title: Stateful Ips
          properties:
            delete_rule:
              name: delete_rule
              title: Delete Rule
              enumValueLabels:
                - label: NEVER
                  value: NEVER
                - label: ON_PERMANENT_INSTANCE_DELETION
                  value: ON_PERMANENT_INSTANCE_DELETION
        target_pools:
          name: target_pools
          title: Target Pools
        target_size:
          name: target_size
          title: Target Size
          level: 1
        update_policy:
          name: update_policy
          title: Update Policy
          properties:
            instance_redistribution_type:
              name: instance_redistribution_type
              title: Instance Redistribution Type
              enumValueLabels:
                - label: PROACTIVE
                  value: PROACTIVE
                - label: NONE
                  value: NONE
            max_surge_percent:
              name: max_surge_percent
              title: Max Surge Percent
              max: 100
            max_unavailable_percent:
              name: max_unavailable_percent
              title: Max Unavailable Percent
              max: 100
            min_ready_sec:
              name: min_ready_sec
              title: Min Ready Sec
              max: 3600
            minimal_action:
              name: minimal_action
              title: Minimal Action
              enumValueLabels:
                - label: RESTART
                  value: RESTART
                - label: REPLACE
                  value: REPLACE
                - label: REFRESH
                  value: REFRESH
                - label: NONE
                  value: NONE
            most_disruptive_allowed_action:
              name: most_disruptive_allowed_action
              title: Most Disruptive Allowed Action
              enumValueLabels:
                - label: REPLACE
                  value: REPLACE
                - label: RESTART
                  value: RESTART
                - label: REFRESH
                  value: REFRESH
                - label: NONE
                  value: NONE
            replacement_method:
              name: replacement_method
              title: Replacement Method
              enumValueLabels:
                - label: RECREATE
                  value: RECREATE
                - label: SUBSTITUTE
                  value: SUBSTITUTE
            type:
              name: type
              title: Type
              enumValueLabels:
                - label: PROACTIVE
                  value: PROACTIVE
                - label: OPPORTUNISTIC
                  value: OPPORTUNISTIC
        wait_for_instances:
          name: wait_for_instances
          title: Wait For Instances
